// ──────────────────────────────────────────────
// Demo profile — hardcoded scenario for first-run
// ──────────────────────────────────────────────

import type { SimulationInput } from '../engine/types';

export const DEMO_PROFILE: SimulationInput = {
  name: 'Demo — Young Professional',
  horizonDays: 365,
  baseCurrency: 'USD',
  fx: {
    baseRates: { EUR: 0.92, PKR: 280 },
    volatility: 0.3,
  },
  startingCash: 5000,
  incomes: [
    {
      id: 'salary',
      name: 'Monthly Salary',
      monthlyAmount: 4200,
      currency: 'USD',
      dayOfMonth: 1,
    },
    {
      id: 'freelance',
      name: 'Freelance Gig',
      monthlyAmount: 800,
      currency: 'USD',
      dayOfMonth: 15,
    },
  ],
  expenses: [
    { id: 'rent', name: 'Rent', monthlyAmount: 1400, currency: 'USD', essential: true },
    { id: 'food', name: 'Food & Groceries', monthlyAmount: 450, currency: 'USD', essential: true },
    { id: 'transport', name: 'Transport', monthlyAmount: 150, currency: 'USD', essential: true },
    { id: 'utils', name: 'Utilities & Internet', monthlyAmount: 180, currency: 'USD', essential: true },
    { id: 'entertainment', name: 'Entertainment', monthlyAmount: 200, currency: 'USD', essential: false },
    { id: 'subscriptions', name: 'Subscriptions', monthlyAmount: 50, currency: 'USD', essential: false },
  ],
  debts: [
    {
      id: 'student_loan',
      name: 'Student Loan',
      principal: 25000,
      currency: 'USD',
      apr: 0.05,
      minPayment: 280,
      missedPayments: 0,
    },
    {
      id: 'credit_card',
      name: 'Credit Card',
      principal: 3200,
      currency: 'USD',
      apr: 0.18,
      minPayment: 100,
      missedPayments: 0,
    },
  ],
  assets: [
    {
      id: 'savings',
      name: 'Savings Account',
      class: 'savings',
      value: 8000,
      currency: 'USD',
      expectedReturn: 0.02,
      volatility: 0.0,
      salePenalty: 0,
      liquidityDelayDays: 0,
      locked: false,
    },
    {
      id: 'index_fund',
      name: 'S&P 500 Index Fund',
      class: 'index_fund',
      value: 3500,
      currency: 'USD',
      expectedReturn: 0.07,
      volatility: 0.15,
      salePenalty: 0,
      liquidityDelayDays: 0,
      locked: false,
    },
    {
      id: 'crypto',
      name: 'Bitcoin',
      class: 'crypto',
      value: 1200,
      currency: 'USD',
      expectedReturn: 0.10,
      volatility: 0.40,
      salePenalty: 0.01,
      liquidityDelayDays: 0,
      locked: false,
    },
  ],
  taxBrackets: [
    { floor: 0, ceiling: 11000, rate: 0.10 },
    { floor: 11000, ceiling: 44725, rate: 0.12 },
    { floor: 44725, ceiling: 95375, rate: 0.22 },
    { floor: 95375, ceiling: 999_999_999, rate: 0.24 },
  ],
  shocks: [
    {
      id: 'medical',
      name: 'Medical Emergency',
      day: 120,
      amount: -5000,
      currency: 'USD',
      enabled: true,
      severity: 1.0,
    },
    {
      id: 'car_repair',
      name: 'Car Repair',
      day: 200,
      amount: -2500,
      currency: 'USD',
      enabled: false,
      severity: 1.0,
    },
    {
      id: 'bonus',
      name: 'Year-End Bonus',
      day: 350,
      amount: 3000,
      currency: 'USD',
      enabled: true,
      severity: 1.0,
    },
    {
      id: 'layoff',
      name: 'Temporary Layoff',
      day: 180,
      amount: -8000,
      currency: 'USD',
      enabled: false,
      severity: 1.0,
    },
    {
      id: 'inheritance',
      name: 'Small Inheritance',
      day: 300,
      amount: 10000,
      currency: 'USD',
      enabled: false,
      severity: 1.0,
    },
  ],
  cashReserveRatio: 0.10,
};
